import Head from 'next/head';

import Banner from '../stories/Banner';
import CustomButton from './../components/Button/CustomButton';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div style={{ display: 'flex' }}>
          <Banner variant='info'>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil
              officiis veniam quidem! Tenetur labore nulla deleniti aut
              molestiae earum, culpa odit commodi fuga cum mollitia quisquam?
              Animi voluptatum perferendis dolorum!
            </p>
          </Banner>

          <Banner variant='danger'>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil
              officiis veniam quidem! Tenetur labore nulla deleniti aut
              molestiae earum, culpa odit commodi fuga cum mollitia quisquam?
              Animi voluptatum perferendis dolorum!
            </p>
          </Banner>
          <Banner variant='congrats'>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil
              officiis veniam quidem! Tenetur labore nulla deleniti aut
              molestiae earum, culpa odit commodi fuga cum mollitia quisquam?
              Animi voluptatum perferendis dolorum!
            </p>
          </Banner>
        </div>
        <div>
          Design system for buttons with classNames package
          <CustomButton className='kkk' type='primary' variant='danger'>
            Lorem
          </CustomButton>
        </div>
      </main>
    </div>
  );
}
